version: '3.8'
services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdb_volume:/data/db
  basketdb:
    container_name: basketgdb
    restart: always
    ports:
      - "6379:6379"
  discount:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discount_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER = admin
      - POSTGRES_PASSWORD = PAssword12*
      - POSTGRES_DB = discountdb
  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA = Y
      - SA_PASSWORD = Password12*
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1444:1433"
    volumes:
      - orderdbdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA = Y
      - SA_PASSWORD = Password12*
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=rabbitmq
      - IdentityServer="http://identityserver.api"
      - DatebaseSettings:ConnectionString=mongodb:catalogdb:27017
    ports:
      - "5011:80"
    depends_on:
      - catalogdb
  identityserver.api:
    container_name: identityserver.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=identitydb,1433;Database=identitydb;User=sa;Password=Password12*"
    ports:
      - "5001:80"
    depends_on:
      - identitydb
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServer="http://identityserver.api"
      - RedisSetting:Port=6379
      - RedisSetting:Host=basketdb
    ports:
      - "5013:80"
    depends_on:
      - basketdb
  photostock.api:
    container_name: photostock.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServer="http://identityserver.api"
    ports:
      - "5012:80"
    volumes:
      - type: bind
        source: C:\Users\GT\Desktop\Kamran
        target: /app/wwwroot/photos
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServer="http://identityserver.api"
      - "ConnectionStrings:DefaultConnection=Server=discountdb;Port=5432;USER ID=admin;Password:Password12*;Database=discountdb;Integrated Security=true;Polling=true"
    ports:
      - "5014:80"
    depends_on:
      - discountdb
  fakepayment.api:
    container_name: fakepayment.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServer="http://identityserver.api"
      - RabbitMQUrl=rabbitmq
    ports:
      - "5016:80"
  order.api:
    container_name: order.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServer="http://identityserver.api"
      - "ConnectionStrings:DefaultConnection=Server=orderdb,1433;Database=orderdb;User=sa;Password=Password12*"
      - RabbitMQUrl=rabbitmq
    ports:
      - "5015:80"
    depends_on:
      - orderdb
  gateway.api:
    container_name: gateway.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - IdentityServer="http://identityserver.api"
    ports:
      - "5000:80"
  frontend.web:
    container_name: frontend.web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ServiceApiSettings:IdentityBaseUri="http://identityserver.api"
      - ServiceApiSettings:GatewayBaseUri=http://gateway.api
    ports:
      - "5010:80"
    depends_on:
      - gateway.api
      - identityserver.api
      - catalog.api
      - basket.api
      - discount.api
      - order.api
      - photostock.api
      - fakepayment.api